/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern ThotBool IsEmptyElement4 (ElementType elType);
extern ThotBool IsCharacterLevelType4 (ElementType elType);
extern ThotBool IsBlockElementType4 (ElementType elType);

#else /* __STDC__ */

extern ThotBool IsEmptyElement4 (ElementType elType);
extern ThotBool IsCharacterLevelType4 (ElementType elType);
extern ThotBool IsBlockElementType4 (ElementType elType);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
