/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__
extern ThotBool IsEmptyElement5 (ElementType elType);
extern ThotBool IsCharacterLevelType5 (ElementType elType);
extern ThotBool IsBlockElementType5 (ElementType elType);

#else /* __STDC__ */

extern ThotBool IsEmptyElement5 (ElementType elType);
extern ThotBool IsCharacterLevelType5 (ElementType elType);
extern ThotBool IsBlockElementType5 (ElementType elType);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
